package config
type Building struct{
	Items []*Building_Item
}

type Building_Item struct{
	Id int
	Type int
	Build_name string
	Max_level int
	Cost_silver int
	Cost_iron int
}

var InstBuilding *Building

func init(){
	item := &Building_Item{}
	item.Id = 1
	item.Type = 0
	item.Build_name = "司令部"
	item.Max_level = 20
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 2
	item.Type = 0
	item.Build_name = "弹药库"
	item.Max_level = 20
	item.Cost_silver = 1800
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 3
	item.Type = 0
	item.Build_name = "银行"
	item.Max_level = 20
	item.Cost_silver = 1800
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 4
	item.Type = 1
	item.Build_name = "弹药车间"
	item.Max_level = 20
	item.Cost_silver = 700
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 5
	item.Type = 1
	item.Build_name = "民居"
	item.Max_level = 20
	item.Cost_silver = 700
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 6
	item.Type = 0
	item.Build_name = "训练场"
	item.Max_level = 20
	item.Cost_silver = 1300
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 7
	item.Type = 0
	item.Build_name = "飞机场"
	item.Max_level = 20
	item.Cost_silver = 3400
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 8
	item.Type = 0
	item.Build_name = "精矿厂"
	item.Max_level = 20
	item.Cost_silver = 3400
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 9
	item.Type = 1
	item.Build_name = "装备车间"
	item.Max_level = 20
	item.Cost_silver = 1900
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 10
	item.Type = 0
	item.Build_name = "科技中心"
	item.Max_level = 20
	item.Cost_silver = 3600
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 11
	item.Type = 0
	item.Build_name = "火车站"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 12
	item.Type = 0
	item.Build_name = "豪华火车站"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 13
	item.Type = 0
	item.Build_name = "军需站"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 14
	item.Type = 0
	item.Build_name = "军用商店"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 15
	item.Type = 0
	item.Build_name = "万能商店"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 16
	item.Type = 0
	item.Build_name = "码头"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 17
	item.Type = 0
	item.Build_name = "军舰"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 18
	item.Type = 0
	item.Build_name = "右下角教堂"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 19
	item.Type = 0
	item.Build_name = "黑市商店"
	item.Max_level = 1
	item.Cost_silver = 0
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
	item = &Building_Item{}
	item.Id = 20
	item.Type = 1
	item.Build_name = "磨坊"
	item.Max_level = 20
	item.Cost_silver = 700
	item.Cost_iron = 0
	InstBuilding.Items = append(InstBuilding.Items,item)
}
