package config
type Jianghun struct{
	Items []*Jianghun_Item
}

type Jianghun_Item struct{
	Id int
	Get_way map[string]int
}

var InstJianghun *Jianghun

func init(){
	item := &Jianghun_Item{}
	item.Id = 310001
	item.Get_way = map[string]int{"1":1049,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310002
	item.Get_way = map[string]int{"1":1018,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310003
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310004
	item.Get_way = map[string]int{"1":1025,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310005
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310006
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":1}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310007
	item.Get_way = map[string]int{"1":1083,"2":1,"3":1,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310008
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310009
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310012
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310013
	item.Get_way = map[string]int{"1":1087,"2":1,"3":0,"4":1}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310016
	item.Get_way = map[string]int{"1":1046,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310017
	item.Get_way = map[string]int{"1":1057,"2":1,"3":1,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310018
	item.Get_way = map[string]int{"1":1062,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310019
	item.Get_way = map[string]int{"1":1070,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310020
	item.Get_way = map[string]int{"1":1010,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310021
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310022
	item.Get_way = map[string]int{"1":1036,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310023
	item.Get_way = map[string]int{"1":1030,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310024
	item.Get_way = map[string]int{"1":1041,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310025
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310026
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310027
	item.Get_way = map[string]int{"1":1079,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310036
	item.Get_way = map[string]int{"1":1016,"2":1,"3":1,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310037
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310038
	item.Get_way = map[string]int{"1":1074,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310039
	item.Get_way = map[string]int{"1":1066,"2":1,"3":0,"4":1}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310040
	item.Get_way = map[string]int{"1":1038,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310042
	item.Get_way = map[string]int{"1":1033,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310043
	item.Get_way = map[string]int{"1":0,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310044
	item.Get_way = map[string]int{"1":1052,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
	item = &Jianghun_Item{}
	item.Id = 310049
	item.Get_way = map[string]int{"1":1020,"2":1,"3":0,"4":0}
	InstJianghun.Items = append(InstJianghun.Items,item)
}
