// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gate_client_msg.proto

package gatemsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_NoError         ErrorCode = 0
	ErrorCode_UnmarshalFailed ErrorCode = 1
	ErrorCode_NoTargetServer  ErrorCode = 2
	ErrorCode_HandShakeFailed ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	0: "NoError",
	1: "UnmarshalFailed",
	2: "NoTargetServer",
	3: "HandShakeFailed",
}

var ErrorCode_value = map[string]int32{
	"NoError":         0,
	"UnmarshalFailed": 1,
	"NoTargetServer":  2,
	"HandShakeFailed": 3,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{0}
}

type MsgTypeGateClient_GateProtocol int32

const (
	MsgTypeGateClient_NotUse              MsgTypeGateClient_GateProtocol = 0
	MsgTypeGateClient_IdBegin             MsgTypeGateClient_GateProtocol = 61184
	MsgTypeGateClient_ClientHandShakeReq  MsgTypeGateClient_GateProtocol = 61185
	MsgTypeGateClient_ClientHandShakeResp MsgTypeGateClient_GateProtocol = 61186
	MsgTypeGateClient_ClientBeatReq       MsgTypeGateClient_GateProtocol = 61187
	MsgTypeGateClient_ClientBeatResp      MsgTypeGateClient_GateProtocol = 61188
	MsgTypeGateClient_GateErrorNt         MsgTypeGateClient_GateProtocol = 61194
	MsgTypeGateClient_IdEnd               MsgTypeGateClient_GateProtocol = 3600
)

var MsgTypeGateClient_GateProtocol_name = map[int32]string{
	0:     "NotUse",
	61184: "IdBegin",
	61185: "ClientHandShakeReq",
	61186: "ClientHandShakeResp",
	61187: "ClientBeatReq",
	61188: "ClientBeatResp",
	61194: "GateErrorNt",
	3600:  "IdEnd",
}

var MsgTypeGateClient_GateProtocol_value = map[string]int32{
	"NotUse":              0,
	"IdBegin":             61184,
	"ClientHandShakeReq":  61185,
	"ClientHandShakeResp": 61186,
	"ClientBeatReq":       61187,
	"ClientBeatResp":      61188,
	"GateErrorNt":         61194,
	"IdEnd":               3600,
}

func (x MsgTypeGateClient_GateProtocol) String() string {
	return proto.EnumName(MsgTypeGateClient_GateProtocol_name, int32(x))
}

func (MsgTypeGateClient_GateProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{0, 0}
}

type MsgTypeGateClient struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgTypeGateClient) Reset()         { *m = MsgTypeGateClient{} }
func (m *MsgTypeGateClient) String() string { return proto.CompactTextString(m) }
func (*MsgTypeGateClient) ProtoMessage()    {}
func (*MsgTypeGateClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{0}
}

func (m *MsgTypeGateClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTypeGateClient.Unmarshal(m, b)
}
func (m *MsgTypeGateClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTypeGateClient.Marshal(b, m, deterministic)
}
func (m *MsgTypeGateClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTypeGateClient.Merge(m, src)
}
func (m *MsgTypeGateClient) XXX_Size() int {
	return xxx_messageInfo_MsgTypeGateClient.Size(m)
}
func (m *MsgTypeGateClient) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTypeGateClient.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTypeGateClient proto.InternalMessageInfo

type GateErrorNt struct {
	CmdId                int32    `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateErrorNt) Reset()         { *m = GateErrorNt{} }
func (m *GateErrorNt) String() string { return proto.CompactTextString(m) }
func (*GateErrorNt) ProtoMessage()    {}
func (*GateErrorNt) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{1}
}

func (m *GateErrorNt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateErrorNt.Unmarshal(m, b)
}
func (m *GateErrorNt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateErrorNt.Marshal(b, m, deterministic)
}
func (m *GateErrorNt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateErrorNt.Merge(m, src)
}
func (m *GateErrorNt) XXX_Size() int {
	return xxx_messageInfo_GateErrorNt.Size(m)
}
func (m *GateErrorNt) XXX_DiscardUnknown() {
	xxx_messageInfo_GateErrorNt.DiscardUnknown(m)
}

var xxx_messageInfo_GateErrorNt proto.InternalMessageInfo

func (m *GateErrorNt) GetCmdId() int32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *GateErrorNt) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type ClientHandShakeReq struct {
	ClientType           string   `protobuf:"bytes,1,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	ClientVersion        string   `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientChannel        string   `protobuf:"bytes,3,opt,name=client_channel,json=clientChannel,proto3" json:"client_channel,omitempty"`
	ClientAuth           string   `protobuf:"bytes,4,opt,name=client_auth,json=clientAuth,proto3" json:"client_auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHandShakeReq) Reset()         { *m = ClientHandShakeReq{} }
func (m *ClientHandShakeReq) String() string { return proto.CompactTextString(m) }
func (*ClientHandShakeReq) ProtoMessage()    {}
func (*ClientHandShakeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{2}
}

func (m *ClientHandShakeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHandShakeReq.Unmarshal(m, b)
}
func (m *ClientHandShakeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHandShakeReq.Marshal(b, m, deterministic)
}
func (m *ClientHandShakeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHandShakeReq.Merge(m, src)
}
func (m *ClientHandShakeReq) XXX_Size() int {
	return xxx_messageInfo_ClientHandShakeReq.Size(m)
}
func (m *ClientHandShakeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHandShakeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHandShakeReq proto.InternalMessageInfo

func (m *ClientHandShakeReq) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *ClientHandShakeReq) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *ClientHandShakeReq) GetClientChannel() string {
	if m != nil {
		return m.ClientChannel
	}
	return ""
}

func (m *ClientHandShakeReq) GetClientAuth() string {
	if m != nil {
		return m.ClientAuth
	}
	return ""
}

type ClientHandShakeResp struct {
	ServerTimeSecond     int32    `protobuf:"varint,1,opt,name=server_time_second,json=serverTimeSecond,proto3" json:"server_time_second,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHandShakeResp) Reset()         { *m = ClientHandShakeResp{} }
func (m *ClientHandShakeResp) String() string { return proto.CompactTextString(m) }
func (*ClientHandShakeResp) ProtoMessage()    {}
func (*ClientHandShakeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{3}
}

func (m *ClientHandShakeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHandShakeResp.Unmarshal(m, b)
}
func (m *ClientHandShakeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHandShakeResp.Marshal(b, m, deterministic)
}
func (m *ClientHandShakeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHandShakeResp.Merge(m, src)
}
func (m *ClientHandShakeResp) XXX_Size() int {
	return xxx_messageInfo_ClientHandShakeResp.Size(m)
}
func (m *ClientHandShakeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHandShakeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHandShakeResp proto.InternalMessageInfo

func (m *ClientHandShakeResp) GetServerTimeSecond() int32 {
	if m != nil {
		return m.ServerTimeSecond
	}
	return 0
}

func (m *ClientHandShakeResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ClientBeatReq struct {
	ReqTime              int32    `protobuf:"varint,1,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientBeatReq) Reset()         { *m = ClientBeatReq{} }
func (m *ClientBeatReq) String() string { return proto.CompactTextString(m) }
func (*ClientBeatReq) ProtoMessage()    {}
func (*ClientBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{4}
}

func (m *ClientBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBeatReq.Unmarshal(m, b)
}
func (m *ClientBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBeatReq.Marshal(b, m, deterministic)
}
func (m *ClientBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBeatReq.Merge(m, src)
}
func (m *ClientBeatReq) XXX_Size() int {
	return xxx_messageInfo_ClientBeatReq.Size(m)
}
func (m *ClientBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBeatReq proto.InternalMessageInfo

func (m *ClientBeatReq) GetReqTime() int32 {
	if m != nil {
		return m.ReqTime
	}
	return 0
}

type ClientBeatResp struct {
	ReqTime              int32    `protobuf:"varint,1,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	ReplyTime            int32    `protobuf:"varint,2,opt,name=reply_time,json=replyTime,proto3" json:"reply_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientBeatResp) Reset()         { *m = ClientBeatResp{} }
func (m *ClientBeatResp) String() string { return proto.CompactTextString(m) }
func (*ClientBeatResp) ProtoMessage()    {}
func (*ClientBeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0615b5f5cf10a6, []int{5}
}

func (m *ClientBeatResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBeatResp.Unmarshal(m, b)
}
func (m *ClientBeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBeatResp.Marshal(b, m, deterministic)
}
func (m *ClientBeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBeatResp.Merge(m, src)
}
func (m *ClientBeatResp) XXX_Size() int {
	return xxx_messageInfo_ClientBeatResp.Size(m)
}
func (m *ClientBeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBeatResp proto.InternalMessageInfo

func (m *ClientBeatResp) GetReqTime() int32 {
	if m != nil {
		return m.ReqTime
	}
	return 0
}

func (m *ClientBeatResp) GetReplyTime() int32 {
	if m != nil {
		return m.ReplyTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("gatemsg.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("gatemsg.MsgTypeGateClient_GateProtocol", MsgTypeGateClient_GateProtocol_name, MsgTypeGateClient_GateProtocol_value)
	proto.RegisterType((*MsgTypeGateClient)(nil), "gatemsg.MsgTypeGateClient")
	proto.RegisterType((*GateErrorNt)(nil), "gatemsg.GateErrorNt")
	proto.RegisterType((*ClientHandShakeReq)(nil), "gatemsg.ClientHandShakeReq")
	proto.RegisterType((*ClientHandShakeResp)(nil), "gatemsg.ClientHandShakeResp")
	proto.RegisterType((*ClientBeatReq)(nil), "gatemsg.ClientBeatReq")
	proto.RegisterType((*ClientBeatResp)(nil), "gatemsg.ClientBeatResp")
}

func init() { proto.RegisterFile("gate_client_msg.proto", fileDescriptor_df0615b5f5cf10a6) }

var fileDescriptor_df0615b5f5cf10a6 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0xeb, 0x9a, 0x24, 0xe4, 0x86, 0x84, 0xe9, 0x4d, 0x2b, 0xa5, 0x12, 0x08, 0x64, 0x09,
	0x09, 0x55, 0x88, 0x0d, 0x4f, 0x40, 0xa3, 0x00, 0x41, 0x22, 0x42, 0x49, 0x5a, 0x89, 0x95, 0x35,
	0x78, 0xae, 0x6c, 0xab, 0xb6, 0xc7, 0x99, 0x99, 0x56, 0xca, 0x8e, 0xbf, 0x15, 0x2b, 0x1e, 0x82,
	0x05, 0x4f, 0xc1, 0xa3, 0xf8, 0x59, 0xd0, 0x8c, 0x1d, 0x64, 0x4a, 0xd5, 0xe5, 0x9c, 0xf3, 0xf9,
	0xcc, 0xdc, 0x73, 0x0d, 0x47, 0x31, 0x37, 0x14, 0x46, 0x59, 0x4a, 0x85, 0x09, 0x73, 0x1d, 0x3f,
	0x2f, 0x95, 0x34, 0x12, 0x7b, 0x56, 0xce, 0x75, 0x1c, 0xfc, 0xf6, 0xe0, 0xe0, 0x9d, 0x8e, 0xd7,
	0xdb, 0x92, 0x5e, 0x73, 0x43, 0x53, 0x07, 0x06, 0xbf, 0x3c, 0xb8, 0x67, 0x8f, 0xef, 0x2d, 0x1c,
	0xc9, 0x0c, 0x01, 0xba, 0x0b, 0x69, 0xce, 0x34, 0xb1, 0x3d, 0x1c, 0x42, 0x6f, 0x2e, 0x4e, 0x29,
	0x4e, 0x0b, 0xf6, 0xa9, 0xf2, 0x71, 0x02, 0x58, 0x7f, 0xf5, 0x86, 0x17, 0x62, 0x95, 0xf0, 0x0b,
	0x5a, 0xd2, 0x86, 0x7d, 0xae, 0x7c, 0x3c, 0x86, 0xf1, 0x7f, 0x8e, 0x2e, 0xd9, 0x97, 0xca, 0xc7,
	0x31, 0x0c, 0x6b, 0xeb, 0x94, 0xb8, 0xb1, 0xfc, 0xd7, 0xca, 0xc7, 0x43, 0x18, 0xb5, 0x45, 0x5d,
	0xb2, 0x6f, 0x95, 0x8f, 0x07, 0x30, 0xb0, 0x4f, 0x99, 0x29, 0x25, 0xd5, 0xc2, 0xb0, 0xef, 0x95,
	0x8f, 0x00, 0x9d, 0xb9, 0x98, 0x15, 0x82, 0xfd, 0x78, 0x10, 0x4c, 0xff, 0xb1, 0xf1, 0x08, 0xba,
	0x51, 0x2e, 0xc2, 0x54, 0x4c, 0xbc, 0xc7, 0xde, 0xd3, 0xce, 0xb2, 0x13, 0xe5, 0x62, 0x2e, 0xf0,
	0x21, 0x00, 0x59, 0x22, 0x8c, 0xa4, 0xa0, 0xc9, 0xbe, 0xb3, 0xfa, 0x4e, 0x99, 0x4a, 0x41, 0xc1,
	0x4f, 0xef, 0xa6, 0x21, 0xf0, 0x11, 0x0c, 0x9a, 0xe6, 0xcc, 0xb6, 0x24, 0x97, 0xd8, 0x5f, 0x42,
	0x2d, 0xd9, 0xc6, 0xf0, 0x09, 0x8c, 0x1a, 0xe0, 0x8a, 0x94, 0x4e, 0x65, 0xe1, 0xa2, 0xfb, 0xcb,
	0x61, 0xad, 0x9e, 0xd7, 0x62, 0x0b, 0x8b, 0x12, 0x5e, 0x14, 0x94, 0x4d, 0xfc, 0x36, 0x36, 0xad,
	0xc5, 0xd6, 0x75, 0xfc, 0xd2, 0x24, 0x93, 0x3b, 0xed, 0xeb, 0x5e, 0x5e, 0x9a, 0x24, 0xf8, 0x70,
	0x63, 0xa1, 0xf8, 0x0c, 0x50, 0x93, 0xba, 0x22, 0x15, 0x9a, 0x34, 0xa7, 0x50, 0x53, 0x24, 0x8b,
	0xdd, 0xfc, 0xac, 0x76, 0xd6, 0x69, 0x4e, 0x2b, 0xa7, 0xe3, 0x21, 0x74, 0x8c, 0xbc, 0xa0, 0xdd,
	0x53, 0xeb, 0x43, 0x70, 0x72, 0x6d, 0x21, 0x78, 0x0c, 0x77, 0x15, 0x6d, 0x5c, 0x62, 0x13, 0xd5,
	0x53, 0xb4, 0xb1, 0x39, 0xc1, 0xdb, 0xeb, 0x7b, 0xba, 0x05, 0xb6, 0xcd, 0x2b, 0x2a, 0xb3, 0x6d,
	0x6d, 0x36, 0xcd, 0x3b, 0xc5, 0xda, 0x27, 0xe7, 0xd0, 0x9f, 0xed, 0xd6, 0x80, 0x03, 0xe8, 0x2d,
	0xa4, 0x3b, 0xb2, 0x3d, 0x1c, 0xc3, 0xfd, 0xb3, 0x22, 0xe7, 0x4a, 0x27, 0x3c, 0x7b, 0xc5, 0xd3,
	0x8c, 0x04, 0xf3, 0x10, 0x61, 0xb4, 0x90, 0x6b, 0xae, 0x62, 0x32, 0x2b, 0x37, 0x18, 0xdb, 0xb7,
	0xe0, 0xdf, 0x3e, 0x1a, 0xd0, 0xff, 0xd8, 0x75, 0xff, 0xf9, 0x8b, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x9b, 0x56, 0x35, 0x00, 0x03, 0x00, 0x00,
}
